# Generated by Django 6.0.7 on 2026-07-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('codigo_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField()),
                ('lotacao', models.IntegerField(blank=True, null=True)),
                ('dia', models.DateField()),
                ('horario', models.TimeField()),
                ('ingresso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField()),
            ],
        ),
    ]
