# Generated by Django 6.0.7 on 2026-08-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemcrud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='ingresso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
